spring.application.name=Hackathon

gemini.api.key= paste api key from ai studio


alphavantage.api.key=0H2UDMSLBJUL5TC4

alphavantage.base.url=https://www.alphavantage.co/query

twelvedata.api.key=8f770cc8068e4a44980d86465d384744

#api key for vantage - 0H2UDMSLBJUL5TC4
